apiVersion: v1
kind: ConfigMap
metadata:
  name: justifications-db
data:
  host: mysql
  justificationsdbname: justifications
  autorizationsdbname: autorizations
  inandoutregdbname: inandoutreg
  categorysdbname: categorys
  configserver: http://config-service:8081
  eurekaserver: http://eureka-service:8761